[versions]
accompanist = "0.32.0"
activity-compose = "1.10.1"
android-gradle-plugin = "8.9.0"
android-junit5 = "1.10.0.0"
coil = "2.5.0"
compose = "1.7.8"
compose-bom = "2025.03.00"
core-ktx = "1.15.0"
constraintlayout-compose = "1.1.1"
espresso-core = "3.6.1"
gplay = "2.0.2"
junit = "5.11.3"
kotlin = "2.1.0"
kotlinx-coroutines-debug = "1.7.3"
libaums = "0.10.0"
libaums-libusbcommunication = "0.3.0"
lifecycle = "2.8.7"
lottie = "6.2.0"
material = "1.12.0"
material3 = "1.3.1"
material3-adaptive = "1.1.0"
mockito = "5.8.0"
robolectric = "4.14"
robolectric-junit5 = "0.9.0"
test-core = "1.6.1"
test-runner = "1.6.2"

# Note for F-Droid developers: Sentry and Firebase are not enabled for F-Droid builds
sentry-lib = "8.4.0"
sentry-plugin = "4.12.0"
firebase-crashlytics = "19.4.2"
google-gms-google-services = "4.4.2"
google-firebase-crashlytics = "3.0.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "google-firebase-crashlytics" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-gms-google-services" }
gplay-sentry-kotlin = { id = "io.sentry.kotlin.compiler.gradle", version.ref = "sentry-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize" }
robolectric-junit5 = { id = "tech.apter.junit5.jupiter.robolectric-extension-gradle-plugin", version.ref = "robolectric-junit5" }

[libraries]
accompanist-navigation-animation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
gplay-review = { group = "com.google.android.play", name = "review", version.ref = "gplay" }
gplay-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "gplay" }
gplay-sentry-android = { group = "io.sentry", name = "sentry-android", version.ref = "sentry-lib" }
gplay-sentry-compose = { group = "io.sentry", name = "sentry-compose-android", version.ref = "sentry-lib" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-debug = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "kotlinx-coroutines-debug" }
libaums-core = { group = "me.jahnen.libaums", name = "core", version.ref = "libaums" }
libaums-libusbcommunication = { group = "me.jahnen.libaums", name = "libusbcommunication", version.ref = "libaums-libusbcommunication" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
test-core = { group = "androidx.test", name = "core", version.ref = "test-core" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebase-crashlytics" }
